name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd codeC
        make
    - name: make test
      run: |
        cd codeC
        make test
    - name: global tests
      run: |
        chmod +x ./test.sh
        ./test.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CyEnedis
        path: codeC/CyEnedis
    - name: make clean
      run: |
        cd codeC
        make clean
