name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -f codeC/Makefile
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: codeC/CyEnedis
